### ISSUE TITLE
Each creature is 1 pixel?

### ISSUE THREAD

**Issue by lodenrogue** [leefogg/Simple-Genetic-Algorithm#1]
Is each creature 1 pixel or is each creature the whole image?

(Great job with this by the way. By generation 1 it starts to look like the image)

Edit: Yes it seems to be. I reworked my previous image generator and now it's very fast and accurate. Thank you for posting this code. It gave me a lot of great ideas.

**Comment by leefogg** [comment]
Yeah each creature is basically one color.
Glad to help!
